name: Publish to NPM

on:
  # This workflow runs on every push to main and can also be triggered manually
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Type check
        run: npm run type-check

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build

      # Automatically bump the patch version, commit, tag, and push.
      # You can change 'patch' to 'minor' or 'major' as needed.
      - name: Bump version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version patch -m "ci: bump version to %s [skip ci]"
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# Notes:
# - This workflow runs on every push to main and will:
#   1. Run tests and type checks.
#   2. Build the package.
#   3. Bump the patch version (change to minor/major if needed), commit, and push the tag.
#   4. Publish the new version to npm.
# - NPM_TOKEN must be set in your repository secrets for publishing to work.
# - GITHUB_TOKEN is used to push the version bump and tag.
# - [skip ci] in the commit message prevents triggering another workflow run from the version bump commit.