name: Publish to NPM

on:
  # This workflow runs when a GitHub Release is published or manually via the Actions tab.
  # To publish on every push to main, replace this with:
  # push:
  #   branches:
  #     - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Type check
        run: npm run type-check

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build

      # Optional: Auto-increment version if not using GitHub Releases for versioning.
      # If you want to bump the version automatically on publish (not recommended with release-based flows),
      # uncomment the following step. This will update package.json, create a git tag, and push it.
      # - name: Bump version
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     npm version patch -m "ci: bump version to %s [skip ci]"
      #     git push --follow-tags
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# Notes:
# - This workflow is triggered by a published GitHub Release or manually.
# - The "Bump version" step is commented out because with release-based publishing,
#   the version should be bumped before creating the release. Uncomment if you want
#   to auto-increment the version on publish (not recommended with release-based flows).
# - NPM_TOKEN must be set in your repository secrets for publishing to work.
# - If you want to auto-publish on every push to main, change the 'on:' section as shown above.